### ISSUE TITLE
Code is unlicensed

### ISSUE THREAD

**Issue by EliseZeroTwo** [derekdreery/vec_box#1]
Hi,

This crate looks useful and I would love to use it but due to the lack of license this is not possible, would it be possible to add a license please?

Thanks,
Elise

**Comment by EliseZeroTwo** [comment]
I just saw the `ISC/MIT/Apache-2.0` in the `Cargo.toml` and the ISC license is valid here so this issue is rendered useless, sorry for not checking further before opening it.

However if I understand them correctly both `MIT` and `Apache-2.0` require you to distribute the license along with the source code which do not appear to be on git.

I will close this issue as it is unrelated but I wanted to point it out.

Sorry again for wasting your time.

**Comment by richard-uk1** [comment]
Hi yeah my philosophy is that I'm always willing to sort out license stuff if people ask, so if you need anything don't hesitate to ask for it :)
